version: "3.9"
services:
  blog:
    container_name: 'blog'
    image: blog:${IMAGE_ID}
    environment:
      - ConnectionStrings__Default=${BLOG_CONNECTIONSTRING}
      - Credentials_AdminEmail=${BLOG_ADMINEMAIL}
      - Credentials_AdminPassword=${BLOG_ADMINPASSWORD}
      - BlogSettings_blogName=${BLOG_NAME}
      - BlogSettings_blogDescription=${BLOG_DESCRIPTION}
      - BlogSettings_newUsersCanRegister=${BLOG_USERSCANREGISTER}
    volumes:
      - ./storage:/app/storage
      - ./logs:/app/logs
    depends_on:
      - "postgres_db"
    networks:
      - postgres

  postgres_db:
    environment:
      POSTGRES_DB: ${DB_DBNAME}
      POSTGRES_USER: ${DB_DBUSER}
      POSTGRES_PASSWORD: ${DB_DBPASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ${DB_HOSTDATAPATH}:/var/lib/postgresql/data
    networks:
      - postgres

networks:
  postgres:
    driver: bridge